config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'

  post 'search' => 'dashboard#search'
  devise_for :users, path: 'users', path_names: { sign_in: 'login', sign_out: 'logout' },
             controllers: {
                sessions: 'users/sessions',
                registrations: 'users/registrations',
                confirmations: 'users/confirmations',
                passwords: 'users/passwords',
                omniauth_callbacks: 'users/omniauth_callbacks'
             }

  ref_resources :tracks do
    get 'download' => 'tracks#download'
    put 'upload'   => 'tracks#upload'
    get 'view'     => 'tracks#view', :as => :view
    get 'gpx'      => 'tracks#gpx', :as => :gpx
  end

  ref_resources(:users) do
    ref_resources :tracks, :only => [:index, :index_items]
  end

  scope :admin do
    ref_resources :layers
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/track.rb
class Track < ActiveRecord::Base
  DEFAULT_COLOR = 'dodgerblue'

  include LibSupport::BaseObject
  include TrackLen

  belongs_to       :user
  belongs_to       :layer
  has_many         :track_items, -> { order(:name) }, foreign_key: :track_code, dependent: :destroy
  strip_attributes :only => [:name, :descr]
  set_ref_columns  :user_name, :name, :len, :avg_speed, :created_at
  set_form_columns :name, :descr, :public
  set_id_column    :code
  paginates_per    10

  validates   :name, :presence => true, :length => { :maximum => 255 }
  validates   :code, :presence => true, :uniqueness => true
  validates   :user, :layer, :presence => true
  validates   :public, :inclusion => { :in => [true, false] }

  set_default_value(:layer) { Layer.first }
  set_default_value(:code) { TmpFiles::gen_hex }

  after_save       :pin_items
  after_commit     { user.refresh_cache }
  after_commit(on: [:create, :update]) { TrackWorker.perform_async(code) unless @lock }  # to calc all distances

  def calc_data!
    ar = []

    track_items.map do |item|
      file = GPX::GPXFile.new(:gpx_data => item.data)

      speed = file.average_speed
      speed = 0 if speed.infinite?

      item.update :len => file.distance, :avg_speed => speed
      ar << { :len => item.len, :avg_speed => item.avg_speed }.methods_for_keys
    end

    @lock = true
    update :len => ar.map(&:len).sum.round(2), :avg_speed => ar.map(&:avg_speed).avg.round(2)
  ensure
    @lock = nil
  end

  def get_data
    TmpFiles.pack name, track_items
  end

  def permit?(*opts)
    user = Permissions.extract_user(*opts)
    public? || permitted_for?(user)
  end

  def permit_modify?(*opts)
    permitted_for? Permissions.extract_user(*opts)
  end

  def self.permitted_for(*opts)
    user = Permissions.extract_user(*opts)
    res = case when user.nil? then where(:public => true)
               when user.admin? then all
            else where(:public => true).or where(:user_id => user.get_id)
          end

    res.with_users
  end

  def track_items
    @items_cache || super
  end

  def track_items=(value)
    @items_cache = (value || {}).map do |_, val|
      {:color => DEFAULT_COLOR}.merge(val.symbolize_keys.delete_if{|__, v| v.nil? || v.to_s.empty? }).methods_for_keys
    end
  end

  def user_name
    user.name
  end

  def self.with_users
    joins(:user).includes(:user)
  end

  private

  def permitted_for?(user)
    user && (user.admin? || user_id.nil? || user_id == user.get_id)
  end

  def pin_items
    return unless @items_cache

    values = @items_cache
    @items_cache = nil

    for_update = values.map{|x| x[:update_id] }.compact
    for_update.each do |id|
      value = values.select{|x| x[:update_id] == id }.first
      item = track_items.where(:id => id).first

      item.update :name => value[:name], :color => value[:color] if item && value
    end

    track_items.where.not(:id => for_update ).destroy_all
    values.select {|x| x[:update_id].nil? }.each { |item|
      TrackItem.create :name => item[:name], :color => item[:color], :track => self,
                       :data => TmpFiles.read(item[:code])
    }
  end
end

app/controllers/tracks_controller.rb
class TracksController < RefsController
  resource_type Track
  layout false, :only => :upload

  before_action :only => [:index, :index_items] do
    @user = User.find_by_id(params[:user_id]) if params[:user_id]
  end

  before_action :only => [:show] do
    redirect_to root_path unless @item && @item.permit_modify?(permission_params)
  end

  before_action :only => [:gpx, :view, :download] do
    @item = resource.find_by_code(params[:track_code])
    forbidden_place unless @item && @item.permit?(permission_params)
  end

  def download
    UserMailer.delay.download_track current_user.id, @item.code
  end

  def gpx
    item = @item.track_items.where(:id => params[:id]).first

    if item
      render xml: item.data
    else
      render body: nil, status: :not_found
    end
  end

  def index_items
    super

    @items = @items.reorder(:created_at => :desc)
    @items = @items.where(:user_id => @user.id) if @user
  end

  def view

  end

  def upload
    render body: nil, status: :unprocessable_entity unless request.content_length <= Rails.application.config.max_attach_size &&
        (@code = TmpFiles.upload(request.raw_post))
  end

  def url_scope(action)
    "/users/#{params[:user_id]}" if action == :index_items && params[:user_id]
  end

  protected

  def resource_params
    params.require(resource.sm_name).permit(:name, :descr, :public, :layer_id, :track_items => [:name, :code, :color, :update_id])
  end

  def update_resource(options = {})
    @item.user ||= current_user

    super
  end
end

app/helpers/tracks_helper.rb
module TracksHelper
  COLOR_LIST = %w(AliceBlue AntiqueWhite Aqua Aquamarine Azure Beige Bisque Black BlanchedAlmond Blue BlueViolet Brown BurlyWood CadetBlue Chartreuse Chocolate Coral CornflowerBlue Cornsilk Crimson Cyan DarkBlue DarkCyan DarkGoldenRod DarkGray DarkGrey DarkGreen DarkKhaki DarkMagenta DarkOliveGreen Darkorange DarkOrchid DarkRed DarkSalmon DarkSeaGreen DarkSlateBlue DarkSlateGray DarkSlateGrey DarkTurquoise DarkViolet DeepPink DeepSkyBlue DimGray DimGrey DodgerBlue FireBrick FloralWhite ForestGreen Fuchsia Gainsboro GhostWhite Gold GoldenRod Gray Grey Green GreenYellow HoneyDew HotPink IndianRed Indigo Ivory Khaki Lavender LavenderBlush LawnGreen LemonChiffon LightBlue LightCoral LightCyan LightGoldenRodYellow LightGray LightGrey LightGreen LightPink LightSalmon LightSeaGreen LightSkyBlue LightSlateGray LightSlateGrey LightSteelBlue LightYellow Lime LimeGreen Linen Magenta Maroon MediumAquaMarine MediumBlue MediumOrchid MediumPurple MediumSeaGreen MediumSlateBlue MediumSpringGreen MediumTurquoise MediumVioletRed MidnightBlue MintCream MistyRose Moccasin NavajoWhite Navy OldLace Olive OliveDrab Orange OrangeRed Orchid PaleGoldenRod PaleGreen PaleTurquoise PaleVioletRed PapayaWhip PeachPuff Peru Pink Plum PowderBlue Purple Red RosyBrown RoyalBlue SaddleBrown Salmon SandyBrown SeaGreen SeaShell Sienna Silver SkyBlue SlateBlue SlateGray SlateGrey Snow SpringGreen SteelBlue Tan Teal Thistle Tomato Turquoise Violet Wheat White WhiteSmoke Yellow YellowGreen)
  def options_colors(value = nil)
    options_from_collection_for_select COLOR_LIST.map(&:downcase), :to_s, :to_s, value
  end
end

app/views/tracks/_item.html.slim
- model = controller.resource.sm_name.to_s
tr data-id="#{item.get_id}" data-type="#{model}"
  td
    input type="checkbox"
  - controller.resource.ref_columns.each do |col|
    - if col == :user_name
      td data-column-name="#{col}"
        - if item.user&.avatar
          = image_tag item.user.avatar.url, :class => 'img-circle-avatar', :title => item.ref_column_value(col)
        = link_to item.ref_column_value(col), user_path(item.user)
    - else
      td data-column-name="#{col}"
        = item.ref_column_value col
  td
    = link_to '#', :class => 'btn-simple btn-editor' do
      i.fa.fa-ellipsis-v
    ul.popup-menu.mui-dropdown__menu.mui-dropdown__menu--right
      = render partial: 'item_buttons', :locals => { :item => item }

app/views/tracks/_item_buttons.html.slim
li
  = link_to track_view_path(item), :target => '_blank' do
    i.fa.fa-map-marker title="#{t('map_long')}"
    span= t('map')
- if item.permit_modify?(controller.permission_params)
  li
    = render partial: 'refs/item_buttons', :locals => {:item => item}
- if user_signed_in?
  li
    = link_to '#', :class => 'btn-track-download' do
      i.fa.fa-download title="#{t('download')}"
      span= t('download')

app/views/tracks/_item_form_buttons.html.slim
.mui-col-md-12
  - if permit_modify
    = form.submit t('lib_support.refs.apply'), :class => 'mui-btn mui-btn--raised mui-btn--primary'
  = link_to t('lib_support.refs.cancel'), user_tracks_path(@item.user || current_user), :class => 'mui-btn mui-btn--raised mx-btn-right'

app/views/tracks/_item_form_fields.html.slim
.mui-col-sm-12.mui-col-md-8
  .mui-textfield.mui-textfield--float-label
    = form.text_field :name, :autofocus => true, :disabled => !permit_modify, :class => "mui--is-empty#{@item.errors.include?(:name) ? ' mx-invalid-value' : ''}"
    - if @item.errors.include?(:name)
      small.mx-error-help-block
        = @item.errors[:name].join
    = form.label :name
.mui-col-sm-12.mui-col-md-4
  .mui-select
    = form.collection_select :layer_id, Layer.all, :id, :name
    = form.label :layer
.mui-col-sm-12
  .mui-textfield.mui-textfield--float-label style="margin-bottom: 0"
    = form.text_area :descr, :disabled => !permit_modify, :class => 'mui--is-empty', :rows => 5, :style => 'resize: vertical'
    = form.label :descr
.mui-col-sm-12
  .mui-checkbox
    label
      = form.check_box :public, :disabled => !permit_modify
      = Track.human_attribute_name(:public)
.mui-col-sm-12
  .track-items
    .track-items-drop-here data-code="#{@item.code}"
- @item.track_items.each_with_index do |item, index|
  .mui-col-sm-12
    = render partial: 'track_item', :locals => { :item => item, :ord => index }
= file_field_tag :track_items_files, :multiple => true, :style => 'display: none'
.mui-col-sm-12
  = link_to '#', :class => 'gpx-file-select' do
    i.fa.fa-paperclip
      span= t('select_files')

app/views/tracks/_track_item.html.haml
- item_value = local_assigns[:item]
- ord_value = local_assigns[:ord] || 0
- code_value = local_assigns[:code]
- color_value = item_value&.color || Track::DEFAULT_COLOR

.input-group.gpx-track-item
  = text_field_tag "track[track_items][#{ord_value}][name]", item_value&.name, :class => 'form-control'
  .input-group-addon.color-addon{:title => t('color_select')}
    %i.fa.fa-map-marker
  .input-group-addon.remove-addon{:title => t('remove_item')}
    %i.fa.fa-times
  = hidden_field_tag "track[track_items][#{ord_value}][code]", code_value || item_value.code, :'data-field' => :code
  = hidden_field_tag "track[track_items][#{ord_value}][color]", color_value, :'data-field' => :color
  - if item_value && item_value.respond_to?(:update_id)
    = hidden_field_tag "track[track_items][#{ord_value}][update_id]", item_value.update_id
.gpx-track-item-color-picker
  .col-xs-12.color-picker
    = select_tag "track[track_items][#{ord_value}][color_selector]", options_colors(color_value), :class => 'form-control'
.gpx-track-item-color-marker{:title => t('color_select'), :style => "background-color: #{color_value}" }

app/views/tracks/_track_item.html.slim
- item_value = local_assigns[:item]
- ord_value = local_assigns[:ord] || 0
- code_value = local_assigns[:code]
- color_value = item_value&.color || Track::DEFAULT_COLOR

.gpx-track-item
  .mui-textfield
    = text_field_tag "track[track_items][#{ord_value}][name]", item_value&.name, :class => 'form-control'
    .remove-addon title="#{t('remove_item')}"
      i.fa.fa-times
  = hidden_field_tag "track[track_items][#{ord_value}][code]", code_value || item_value.code, :'data-field' => :code
  = hidden_field_tag "track[track_items][#{ord_value}][color]", color_value, :'data-field' => :color
  - if item_value && item_value.respond_to?(:update_id)
    = hidden_field_tag "track[track_items][#{ord_value}][update_id]", item_value.update_id
.gpx-track-item-color-picker
  .color-picker
    = select_tag "track[track_items][#{ord_value}][color_selector]", options_colors(color_value), :class => 'form-control'
.gpx-track-item-color-marker title="#{t('color_select')}" style="background-color: #{color_value}"

app/views/tracks/index.html.haml
- if @user
  - breadcrumb :user_tracks, @user
- else
  - breadcrumb :tracks

= render partial: 'index'

app/views/tracks/index.html.slim
- if @user
  - breadcrumb :user_tracks, @user
- else
  - breadcrumb :tracks

= render partial: 'index'

app/views/tracks/upload.html.slim
= render partial: 'track_item', :locals => { :code => @code }

app/views/tracks/view.html.haml
= javascript_include_tag :leaflet, :gpx, :'data-turbolinks-track' => 'reload'
= stylesheet_link_tag    :leaflet, media: 'all', :'data-turbolinks-track' => 'reload'
- content_for :map_view, true
- content_for :page_title, @item.name
#map{:'data-url' => @item.layer.url, :'data-tracks' => @item.track_items.map{|x| { :id => x.id, :color => x.color, :name => x.name, :url => track_gpx_path(@item, :id => x.id) } }.to_json.html_safe }
#legend
  .show-legend{:title => t('show_legend')}
    %i.fa.fa-info-circle
  .info-header
    %h4= @item.name
    .hide-legend{:title => t('hide_legend')}
      %i.fa.fa-times
  .legend_text= (@item.descr || '').html_safe
  .legend_items
    - @item.track_items.each do |item|
      .legend_row
        .legend_item.item-checkbox
          = check_box_tag "item[#{item.id}]", nil, true, :'data-id' => item.id
        .legend_item.color
          %div{:style => "background-color: #{item.color}"}
        .legend_item
          = "#{item.name} (#{item.len} #{t('km')})"

app/views/tracks/view.html.slim
= javascript_include_tag :leaflet, :gpx, :'data-turbolinks-track' => 'reload'
= stylesheet_link_tag    :leaflet, media: 'all', :'data-turbolinks-track' => 'reload'
- content_for :map_view, true
- content_for :page_title, @item.name

#map data-url="#{@item.layer.url}" data-tracks="#{@item.track_items.map{|x| { :id => x.id, :color => x.color, :name => x.name, :url => track_gpx_path(@item, :id => x.id) } }.to_json}"
#legend
  .show-legend title="#{t('show_legend')}"
    i.fa.fa-info-circle
  .info-header
    h4= @item.name
    .hide-legend title="#{t('hide_legend')}"
      i.fa.fa-times
  .legend_text= (@item.descr || '').html_safe
  .legend_items
    - @item.track_items.each do |item|
      .legend_row
        .legend_item.item-checkbox
          = check_box_tag "item[#{item.id}]", nil, true, :'data-id' => item.id
        .legend_item.color
          div style="background-color: #{item.color}"
        .legend_item
          = item.name
          span = "  (#{item.len} #{t('km')}, #{item.avg_speed.round(2)} #{t('kmh')})"