config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'

  post 'search' => 'dashboard#search'
  devise_for :users, path: 'users', path_names: { sign_in: 'login', sign_out: 'logout' },
             controllers: {
                sessions: 'users/sessions',
                registrations: 'users/registrations',
                confirmations: 'users/confirmations',
                passwords: 'users/passwords',
                omniauth_callbacks: 'users/omniauth_callbacks'
             }

  ref_resources :tracks do
    get 'download' => 'tracks#download'
    put 'upload'   => 'tracks#upload'
    get 'view'     => 'tracks#view', :as => :view
    get 'gpx'      => 'tracks#gpx', :as => :gpx
  end

  ref_resources(:users) do
    ref_resources :tracks, :only => [:index, :index_items]
  end

  scope :admin do
    ref_resources :layers
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/views/layouts/_nav.html.slim
#sidedrawer-brand.mui--appbar-line-height
  = link_to root_path, :class => 'favicon' do
    = image_tag '/favicon.ico'
    = t('title')
.mui-divider
ul
  li
    strong= t('instances')
    ul
      li= link_to User.model_name.human(:count => 2), users_path
      - if user_signed_in? && current_user.admin?
        li= link_to Layer.model_name.human(:count => 2), layers_path
      li= link_to Track.model_name.human(:count => 2), tracks_path
  li
    strong= I18n.t('profile')
    - if user_signed_in?
      ul
        li= link_to t('profile'), user_path(current_user)
        li= link_to t('add_track'), new_track_path
        li= link_to t('my_tracks'), user_tracks_path(current_user)
        li= link_to t('sign_out'), destroy_user_session_path, :method => :delete
    - else
      ul
        li= link_to t('sign_in'), new_user_session_path

app/views/layouts/application.html.slim
- map_view = content_for?(:map_view)
- page_title = content_for(:page_title)

doctype html
html
  head
    meta content=('text/html; charset=UTF-8') http-equiv="Content-Type"
    title= page_title ? "#{page_title} - #{t('title')}" : t('title')
    meta charset="UTF-8"
    meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"
    meta content="width=device-width, initial-scale=1" name="viewport"
    = csrf_meta_tags
    = action_cable_meta_tag
    = stylesheet_link_tag    'application', media: 'all', :'data-turbolinks-track' => 'reload'
    = javascript_include_tag 'application', :'data-turbolinks-track' => 'reload'
  = content_tag :body, :class => current_page?(root_path) ? 'hide-sidedrawer' : 'no-overlay' do
    - if map_view
      = yield
    - else
      #sidedrawer.mui--no-user-select
        = render partial: 'layouts/nav'
      header#header
        table.mui-appbar width='100%'
          tr style='vertical-align:middle'
            td.mui--appbar-line-height style="white-space: nowrap"
              .mui-container-fluid
                .sidedrawer-toggle.mui--visible-xs-inline-block.js-show-sidedrawer
                  i.fa.fa-bars
                .sidedrawer-toggle.mui--hidden-xs.js-hide-sidedrawer
                  i.fa.fa-bars
                .breadcrumbs
                  - breadcrumbs.tap do |links|
                    - if links.any?
                      - links.each do |link|
                        - if link.current?
                          span= link.text
                        -else
                          = link_to link.text, link.url
                          i.fa.fa-angle-right
            td.mui--appbar-height.mui--text-right
              - if controller.respond_to?(:resource) && action_name == 'index'
                .mui-container-fluid.search-bar
                  .mui-textfield
                    input type="text" placeholder="#{t('lib_support.refs.search')}" data-action="search" data-type="#{controller.resource.sm_name}"
                  = link_to '#', :class => 'btn-simple btn-search-show' do
                    i.fa.fa-search
                  = link_to '#', :class => 'btn-simple btn-search-hide' do
                    i.fa.fa-times
      #content-wrapper
        .mui--appbar-height
        .mui-container-fluid.mui-main-container data-instance="#{content_for(:base_page).blank?.to_s}"
          .mui-row
            .mui-col-sm-10.mui-col-sm-offset-1
              = yield